Tests ran at 10 Apr 02 20 PM

65 tests passed out of 65 tests.

tests.py::test_create_post_with_invalid_user_id_raise_exception: passed
tests.py::test_create_post_with_invalid_post_content_raise_exception: passed
tests.py::test_create_post_with_valid_user_and_valid_post_content_return_post_id: passed
tests.py::test_create_comment_to_post_with_invalid_post_id_raise_exception: passed
tests.py::test_create_comment_to_post_with_invalid_user_id_raise_exception: passed
tests.py::test_create_comment_to_post_with_invalid_comment_content: passed
tests.py::test_create_comment_with_valid_details_return_comment_id: passed
tests.py::test_reply_to_comment_with_invalid_comment_id_raise_exception: passed
tests.py::test_reply_to_comment_with_invalid_user_id_raise_exception: passed
tests.py::test_reply_to_comment_with_invalid_reply_content_raise_exception: passed
tests.py::test_reply_to_comment_with_valid_details_return_comment_id: passed
tests.py::test_reply_to_reply_with_valid_details_return_comment_id: passed
tests.py::test_react_to_post_with_invalid_user_id_raise_exception: passed
tests.py::test_react_to_post_with_invalid_post_id_raise_exception: passed
tests.py::test_react_to_post_with_invalid_reaction_type_raise_exception: passed
tests.py::test_react_to_post_with_valid_details_create_new_reaction_to_post: passed
tests.py::test_react_to_post_with_valid_details_and_update_reaction_type: passed
tests.py::test_react_to_post_with_valid_deatils_and_same_previous_reaction_type_delete_reaction: passed
tests.py::test_react_to_comment_with_invalid_user_id_raise_exception: passed
tests.py::test_react_to_comment_with_invalid_comment_id_raise_exception: passed
tests.py::test_react_to_comment_with_invalid_reaction_type_raise_exception: passed
tests.py::test_react_to_comment_with_valid_details_create_new_reaction_to_comment: passed
tests.py::test_react_to_comment_with_valid_details_and_update_reaction_type: passed
tests.py::test_react_to_comment_with_valid_deatils_and_same_previous_reaction_type_delete_reaction: passed
tests.py::test_get_total_reactions_count_for_all_users: passed
tests.py::test_get_total_reactions_count_for_all_users_when_no_reactions_db: passed
tests.py::test_get_reaction_metrics_with_invalid_post_raise_exception: passed
tests.py::test_get_reaction_metrics_with_valid_post_returns_reaction_metrics: passed
tests.py::test_delete_post_with_invalid_user_id_raise_exception: passed
tests.py::test_delete_post_with_invalid_post_raise_exception: passed
tests.py::test_delete_post_with_invalid_user_post_raise_exception: passed
tests.py::test_delete_post_with_valid_post_and_delete_post: passed
tests.py::test_get_posts_with_more_positive_reactions_returns_post_ids_list: passed
tests.py::test_get_posts_reacted_by_user_with_invalid_user_raise_exception: passed
tests.py::test_get_posts_reacted_by_user_with_valid_details_return_reacted_post_ids: passed
tests.py::test_get_reactions_to_post_with_invalid_post_id_raise_exception: passed
tests.py::test_get_reactions_to_post_with_valid_details_return_list_of_user_dicts_with_reaction: passed
tests.py::test_get_replies_for_comment_with_invalid_comment_raise_exception: passed
tests.py::test_get_replies_for_comment_with_valid_comment_returns_comments: passed
tests.py::test_get_post_with_invalid_post_id_raise_exception: passed
tests.py::test_get_post_with_valid_details_return_post_details: passed
tests.py::test_get_user_posts_with_valid_details_return_user_posts_details: passed
tests.py::test_performance_of_create_post_with_valid_user_returns_valid_post: passed
tests.py::test_performance_of_create_comment_to_post_with_valid_details_return_comment_id: passed
tests.py::test_performance_of_reply_to_comment_with_valid_details_return_reply_id: passed
tests.py::test_performance_of_reply_to_reply_comment_with_valid_details_returns_reply_id: passed
tests.py::test_performance_of_react_to_post_with_valid_details_and_create_new_reaction: passed
tests.py::test_performance_of_react_to_post_with_valid_details_and_update_previous_reaction: passed
tests.py::test_performance_of_react_to_post_with_valid_details_and_delete_reaction: passed
tests.py::test_performance_of_react_to_comment_with_valid_details_and_create_new_reaction: passed
tests.py::test_performance_of_react_to_comment_with_valid_details_and_update_previous_reaction: passed
tests.py::test_performance_of_react_to_comment_with_valid_details_and_same_previous_reaction_type_delete_reaction: passed
tests.py::test_performance_of_delete_post_with_valid_post_returns_exception: passed
tests.py::test_performance_of_get_posts_with_more_positive_reactions_returns_post_ids_list: passed
tests.py::test_performance_of_get_posts_reacted_by_user_with_valid_details_return_reacted_post_ids: passed
tests.py::test_performance_of_get_total_reactions_count_for_all_users: passed
tests.py::test_performance_of_get_reaction_metrics_with_valid_post_returns_reaction_metrics: passed
tests.py::test_performance_of_get_replies_for_comment_with_valid_comment_returns_comments: passed
tests.py::test_performance_of_get_post_with_valid_details_return_post_details: passed
tests.py::test_performance_of_get_user_posts_with_valid_details_return_user_posts_details: passed
tests.py::test_user_model: passed
tests.py::test_post_model: passed
tests.py::test_comment_model: passed
tests.py::test_comment_model_to_support_reply: passed
tests.py::test_reaction_model: passed


Errors: 0 errors

